### ISSUE TITLE
unity-delaunay to triangulate 2D mesh for bitmap images

### ISSUE THREAD

**Issue by ForouzanFn** [OskarSigvardsson/unity-delaunay#3]
Hello

I want to use your unity-delaunay to triangulate 2D mesh for bitmap images.
Could you help me what should I do?

Thanks

**Comment by OskarSigvardsson** [comment]
Could you explain a bit further what you mean? You have a bitmap of some sort, and you want to triangulate it? Triangulate it in what way? Where should the triangles be?

**Comment by ForouzanFn** [comment]
Hello

I want to implement a prototype in unity that input is a bitmap image and
after that triangulate image. For example like this attached image.

Thanks

**Comment by OskarSigvardsson** [comment]
When you respond using email, your image attachment doesn't show up for me. If you go to the issue page on GitHub, here: 

https://github.com/OskarSigvardsson/unity-delaunay/issues/3

And put the image in a comment there, then I can see it.

**Comment by ForouzanFn** [comment]
I want to implement a prototype in unity that input is a bitmap image and after that triangulate image. For example like this attached image.

![photo_2019-07-11_14-07-38](https://user-images.githubusercontent.com/52780822/61041235-44e2d500-a3e7-11e9-8eea-e1863dafd2fc.jpg)

**Comment by ForouzanFn** [comment]
I put my image.

thanks.

**Comment by OskarSigvardsson** [comment]
I see. No, this library cannot, by itself, do what you want to do. It could be a lower-level component in a library that maybe could do this, but it would require a lot of work. 

This is a quite difficult problem you want to solve. In order to do that, you would have to do two things: 

1. Fit a polygon around the edges of your sprite
2. Triangulate that polygon

Number 2 is relatively straightforward, you can use the "ear clipping" method described on [the Wikipedia page for "polygon triangulation"](https://en.wikipedia.org/wiki/Polygon_triangulation). The resulting mesh wont be as nice and clean as yours is, but that is where you could use this library in order to "clean it up" and make it nicer. 

Number 1 is a much harder problem to solve, and extremely difficult to do in an automated fashion efficiently. I can't think of a straightforward way that doesn't result in a terrible mesh. 

I want to ask: why do you want to do this? If you just want to render a sprite without a background, you can just use alpha blending instead, it is a far better method. In any case, you should rethink if this is something you actually want to do. 

I'm closing this issue because it's not really relevant to the library, but feel free to keep asking if you have further questions.

**Comment by ForouzanFn** [comment]
thanks for your help. I am implementing one game that input is bitmap image
and for animate the bitmap image I should do this action.

**Comment by OskarSigvardsson** [comment]
Ok. I would probably figure out another solution than trying to triangulate the sprite like this, but maybe you can make it work. Good luck.

**Comment by ForouzanFn** [comment]
Thank you. If you figure out another solution, could you please tell me what should I do?
