### ISSUE TITLE
Sites close together are not calculated in the Voronoi diagram.

### ISSUE THREAD

**Issue by EmreDogann** [OskarSigvardsson/unity-delaunay#5]
Hey there, I recently started using your library but I've encountered an issue where the Voronoi diagram is not computed correctly when the points are distributed close to each other. This is a pretty big deal for me as I need to created small fragments instead of larger ones like those shown in the gif on the readme.

I want to use this library for simple destruction of walls where I create a simple small hole in a wall where the player shoots or a large hole that the player can go through if they use an explosive weapon.

Attached I have examples of what I am talking about. The red lines are for the Voronoi diagram, the tiny green dots spheres are the site coordinates, and the blue lines are for the Delaunay triangulation.

### This is an example of a Voronoi diagram on its own:
![Voronoi Diagram](https://user-images.githubusercontent.com/48212096/75901108-f41c6280-5e35-11ea-9b1c-5efe3d4b0049.png)

### This is another example of a Voronoi diagram but _also_ with it's Delaunay triangulation:
![Voronoi Diagram with Delaunay Triangulation](https://user-images.githubusercontent.com/48212096/75901109-f4b4f900-5e35-11ea-9f38-2cd9169ce027.png)

These were displayed using Gizmos in Unity.

As you can see, I don't think the problem is with how I'm rendering the diagrams which was my first assumption, but instead, it has to be a problem with something inside VoronoiCalculator.cs as the Delaunay triangulation looks as expected.

The code I'm using is down below:
```
namespace GK
{
    public class VoronoiDestruction : MonoBehaviour
    {
        [Range(0, 1000)]
        public int points = 100;
        [Range(0.0f, 10.0f)]
        public float mean = 0;
        [Range(0.0f, 10.0f)]
        public float stddev = 0.2;

        Vector2[] sites;
        VoronoiDiagram diagram = new VoronoiDiagram();
        DelaunayTriangulation trig = new DelaunayTriangulation();

        void Start()
        {
            sites = new Vector2[points];
        }

        void OnDrawGizmos()
        {
            if (Application.isPlaying)
            {
                Gizmos.color = Color.green;
                if (sites.Length > 0)
                {
                    // Draw Voronoi sites.
                    for (int i = 0; i < sites.Length; i++)
                    {
                        Vector2 worldVert = transform.TransformPoint(sites[i]);
                        Gizmos.DrawSphere(new Vector3(worldVert.x, worldVert.y, 4), 0.01f);
                    }

                    // Draw Voronoi edges.
                    Gizmos.color = Color.red;
                    for (int i = 0; i < diagram.Edges.Count; i++)
                    {
                        VoronoiDiagram.Edge edge = diagram.Edges[i];
                        Vector2 worldVert = transform.TransformPoint(diagram.Vertices[edge.Vert0]);
                        if (edge.Type == VoronoiDiagram.EdgeType.RayCW || edge.Type == VoronoiDiagram.EdgeType.RayCCW)
                        {
                            //Vector2 worldDir = transform.TransformPoint(edge.Direction);
                            Vector2 worldDir = edge.Direction;
                            Gizmos.DrawRay(new Vector3(worldVert.x, worldVert.y, 4), new Vector3(worldDir.x, worldDir.y, 0));
                        }
                        else if (edge.Type == VoronoiDiagram.EdgeType.Segment)
                        {
                            Vector2 worldVert2 = transform.TransformPoint(diagram.Vertices[edge.Vert1]);
                            Gizmos.DrawLine(new Vector3(worldVert.x, worldVert.y, 4), new Vector3(worldVert2.x, worldVert2.y, 4));
                        }
                    }

                    // Draw Delaunay triangulation.
                    Gizmos.color = Color.blue;
                    for (int i = 0; i < trig.Triangles.Count; i += 3)
                    {
                        Vector2 worldVert1 = transform.TransformPoint(trig.Vertices[trig.Triangles[i]]);
                        Vector2 worldVert2 = transform.TransformPoint(trig.Vertices[trig.Triangles[i + 1]]);
                        Vector2 worldVert3 = transform.TransformPoint(trig.Vertices[trig.Triangles[i + 2]]);
                        Gizmos.DrawLine(new Vector3(worldVert1.x, worldVert1.y, 4), new Vector3(worldVert2.x, worldVert2.y, 4));
                        Gizmos.DrawLine(new Vector3(worldVert1.x, worldVert1.y, 4), new Vector3(worldVert3.x, worldVert3.y, 4));
                        Gizmos.DrawLine(new Vector3(worldVert2.x, worldVert2.y, 4), new Vector3(worldVert3.x, worldVert3.y, 4));
                    }
                }
            }
        }

        public void redrawDiagram(Vector3 pos)
        {
            Vector3 temp = transform.InverseTransformPoint(pos);
            Vector2 position = new Vector2(temp.x, temp.y);

            var calc = new VoronoiCalculator();

            sites = new Vector2[points];

            for (int i = 0; i < sites.Length; i++)
            {
                //var dist = Mathf.Abs(NormalizedRandom(10.0f, 1.0f / 2.0f));
                var dist = Mathf.Abs(NormalizedRandom(mean, stddev));
                var angle = 2.0f * Mathf.PI * Random.value;

                sites[i] = position + new Vector2(
                        dist * Mathf.Cos(angle),
                        dist * Mathf.Sin(angle));
            }

            diagram = calc.CalculateDiagram(sites);
            trig = diagram.Triangulation;
        }

        private float NormalizedRandom(float mean, float stddev)
        {
            var u1 = UnityEngine.Random.value;
            var u2 = UnityEngine.Random.value;

            var randStdNormal = Mathf.Sqrt(-2.0f * Mathf.Log(u1)) *
                Mathf.Sin(2.0f * Mathf.PI * u2);

            return mean + stddev * randStdNormal;
        }
    }
}
```

Do you know why this might be and if there is a way to solve this?

EDIT: Forgot to mention, `redrawDiagram(Vector3 pos)` is called when the player shoots the wall. A 'shooting' script is attached to the camera, when left click is pressed, a raycast is shot out and if it hits the wall, it calls redrawDiagram and feeds in the position where the raycast hit as `pos`.

**Comment by EmreDogann** [comment]
I have managed to fix the issue.

The LineLineIntersection method inside the **Geom.cs** file (**line 77**) was making a check where it would not calculate the line/line intersection if the variable det was **less than 0.001f.** I decreased the value from 0.001 to 0.00000001 and now it seems to correctly calculate the voronoi diagram for points that are close together.

Below are screenshots of the generated voronoi diagrams after the fix:
https://imgur.com/a/J6Np1ov

**Comment by OskarSigvardsson** [comment]
@EmreDogann Hey, yeah, sorry for not responding, it's been a crazy few weeks (for all of us, I imagine!). I'm only now going through my github issues. 

Yeah, the epsilon value is needed because of floating point imprecision issues, but there's no "right answer" to what the size of it should be. It depends on the scale your game is running at. 0.001 is maybe a bit high though. I'll consider decreasing decreasing it. 

If you wind up using this library in a game, let me know about it! I would love to hear about it!

**Comment by EmreDogann** [comment]
No worries! Now that I've fixed the issue, I've been toying around with different ways to do destruction with the library.

My idea is i want different surfaces to behave differently when being destroyed. For surfaces that shatter (glass, wood, tiles, etc.) This can be easily achieved by playing around with the random generation of sites. However, my main goal for this destruction system is to be able to shoot holes in walls (not completely shatter). The solutions I've tried up until now using this library have all yielded me a complexity of O(n^2), which i could optimize a little. To my knowledge the bower-watson algorithm doesn't support constrained Delaunay triangulation. So i had to manually check for the holes myself.

Right now, im working on implementing a system where i use this library along with voxels to determine which voxels to apply a force to based on the site's location. As my walls are all pretty basic, i can get away with building a quadtree for the voxels instead of octree. Now i could optimize this to avoid Unity's physics system from dominating cpu time by have the wall blow off in chunks instead of individual voxels, but once again I'm going to have to play around with that.

That's where i am right now, just experimenting to see what works and what doesn't, if you have any additional insight i would be very grateful if you share it with me! It's an absolutely awesome library, out of all the other triangulation/voronoi generation libraries I've tried this is still by far the most efficient and garbage friendly.

**Comment by OskarSigvardsson** [comment]
Sounds like a really cool system! I'm eager to see where it goes. 

> However, my main goal for this destruction system is to be able to shoot holes in walls (not completely shatter).

It's an interesting problem. Of the top of my head I'm thinking "cut the whole out first, then shatter the 'cut-out'". Like, you figure out what the shape of the hole is, then do like a boolean subtraction thing from the wall, then shatter the cut-out hole. But it would be tricky, if you then wanted to make more hole, because the wall is no longer a convex shape, so you can't easily clip to it. 

Another idea (which might not work at all, I'm just speculating) is to make an additional "ring" of shards, and freeze those. Like, the way the destruction effect works at the moment is to generate a "ring" of sites at random angles and random distances (the random distance normalized around some value). Instead of doing that, you could do, like, two rings of sites. The shards from the "inner" ring works like normal, but the shards from the outer rings are frozen and static. The inner ring of shards would thus punch a hole in the outer ring of shards (the outer ring of shards would then not look like shards, just like the wall that's still standing). 

You might have seen it already, but I also made a different kind of destruction effect in 3D a while back, but I never properly finished it. `[Here it is](https://github.com/OskarSigvardsson/quickfracture)`.  It's on my list of things to go back to and develop further. 

> That's where i am right now, just experimenting to see what works and what doesn't, if you have any additional insight i would be very grateful if you share it with me! It's an absolutely awesome library, out of all the other triangulation/voronoi generation libraries I've tried this is still by far the most efficient and garbage friendly.

That's awesome to hear! The whole reason I did the library in the first place was that I couldn't find a Voronoi library that I thought worked well enough that was suitable for Unity. And I basically couldn't find any Voronoi library whatsoever that could clip the diagrams to arbitrary convex shapes, so I thought the "recursive" version would be genuinely innovative. I also couldn't find any papers describing how to do it, so I more or less had to come up with it myself (it's a relatively straight-forward adaptation of the Sutherland-Hodgman clipping algorithm). 

I did go to some length to make it something I would feel comfortable to use in production (I used to work in Unity gamedev, now it's just a hobby), so I went to some trouble to make sure it was both fast and it gave you options to avoid generating excessive garbage. It clearly paid off!

I occasionally see people posting clips of their Unity prototype/games which use Voronoi tessellations and wonder to myself if they're using my library ([this, for instance](https://www.reddit.com/r/Unity3D/comments/fduvom/working_on_a_procedural_iceberg_creation_and/)). I'm not litigious or anything, I'm happy for anyone to use it, but it would be nice to know for sure :) 

I hope you use it to make something cool! Good luck.

**Comment by EmreDogann** [comment]
> It's an interesting problem. Of the top of my head I'm thinking "cut the whole out first, then shatter the 'cut-out'". Like, you figure out what the shape of the hole is, then do like a boolean subtraction thing from the wall, then shatter the cut-out hole. But it would be tricky, if you then wanted to make more hole, because the wall is no longer a convex shape, so you can't easily clip to it.
> 
> Another idea (which might not work at all, I'm just speculating) is to make an additional "ring" of shards, and freeze those. Like, the way the destruction effect works at the moment is to generate a "ring" of sites at random angles and random distances (the random distance normalized around some value). Instead of doing that, you could do, like, two rings of sites. The shards from the "inner" ring works like normal, but the shards from the outer rings are frozen and static. The inner ring of shards would thus punch a hole in the outer ring of shards (the outer ring of shards would then not look like shards, just like the wall that's still standing).

While these could work, it still runs into the same issue i had before. I haven't been able to find a way to efficiently cut out only a part of the mesh. The way i did it was, when the player shoots, i generate a cluster of points, then i get the vertices of the site the player hit (using clipper). After this i redo the delaunay triangulation (not the voronoi though, just the triangulation) and pass in the vertices of the outer mesh (in this case 4 verticies for a quad) along with the verticies of the site i just found to work out the new triangles. Now the problem is the triangulation fills in the hole i want with triangles (as it cannot tell the difference between verticies for holes and those for the outer mesh), so i end up manually looping through it and removing those triangles. It works, but is not nearly fast enough for me (because the player can repetedly shoot the wall, more and more holes will be created, slowing it down dramatically. I cannot precalculate the destruction either as all my guns use ray casts). Along with that, with my method, i would run into issues of overlapping holes.

> so I went to some trouble to make sure it was both fast and it gave you options to avoid generating excessive garbage. It clearly paid off!

I've actually gotten the "holes in walls" system working in several other libraries (Triangle.Net being one of them), however the issue always came down to performance, the libraries weren't nearly as performant or garbage friendly as i would have liked. I would have terrible performance that got out of control fast no matter how much i tried to optimize (mainly because those libraries weren't built for my purposes). Your library is really the only one that's built for procedural generation like this.

I'm probably not knowledgeable enough to figure it out but gosh darn it I'm gonna try as hard as i can! The whole experimentation stage to me is just as enjoyable as seeing my vision come to life!

Thanks for the kind words, I'll see what i can achieve with your suggestions!
